# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Kevin Chaplin
email: kevinchaplin58@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The life and work of Kevin Chaplin.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://oboekevin.github.io" # the base hostname & protocol for your site
twitter_username: kchappers58
github_username:  oboekevin
instagram_username: kchappers58

# Build settings
markdown: kramdown
# Added 9-19-17
include: ["_pages"]

# theme: jekyll-theme-slate
